url: https://austin-capital-data.github.io
baseurl: ""

# Site settings
title: Austin Capital Data
email: gunnar@austincapitaldata.com
description: "A place for people to discuss thier creations"


# Team names, titles and social links
people:
- name: Justine Chia
  pic: 1
  position: Data Scientist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Mayra Castro
  pic: 2
  position: Project management
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Skylar Chadwick
  pic: 3
  position: Content strategist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 9701 Dessau Rd #304
  - line: Austin, TX 78754

# Build settings
markdown: kramdown
permalink: pretty
